DESCRIPTIONS = {
    "fs.defaultFS": "Hadoop默认文件系统URI，客户端使用相对路径时自动添加此前缀。如 hdfs://namenode:8020 或 hdfs://mycluster(HA模式)",
    "hadoop.tmp.dir": "Hadoop运行时临时文件存储位置，包含中间结果和日志。需确保磁盘空间充足",
    "hadoop.http.staticuser.user": "通过Web界面访问HDFS时使用的默认用户身份",
    "io.file.buffer.size": "Hadoop I/O操作的缓冲区大小(字节)，影响文件读写性能。默认4096(4KB)，建议设为65536(64KB)",
    "io.compression.codecs": "Hadoop支持的压缩编解码器列表，逗号分隔。常用: SnappyCodec, GzipCodec, Lz4Codec, BZip2Codec",
    "io.serializations": "Hadoop序列化框架列表，默认org.apache.hadoop.io.serializer.WritableSerialization",
    "hadoop.security.authentication": "Hadoop安全认证模式: simple(无认证)或kerberos(Kerberos认证)",
    "hadoop.security.authorization": "是否启用Hadoop服务级授权，true后需配置hadoop-policy.xml",
    "hadoop.proxyuser.root.hosts": "root用户代理访问允许的主机列表，*表示所有主机。Oozie/Hive等需要代理功能",
    "hadoop.proxyuser.root.groups": "root用户代理访问允许的用户组列表，*表示所有组",
    "hadoop.proxyuser.httpfs.hosts": "HTTP代理用户允许的主机列表",
    "hadoop.proxyuser.httpfs.groups": "HTTP代理用户允许的用户组列表",
    "hadoop.proxyuser.hive.hosts": "Hive代理用户允许的主机列表",
    "hadoop.proxyuser.hive.groups": "Hive代理用户允许的用户组列表",
    "dfs.replication": "HDFS数据块副本数量，影响数据可靠性和读取性能。推荐值3，实验环境可设2",
    "dfs.namenode.name.dir": "NameNode元数据在本地文件系统的存储目录，包含fsimage和edits日志。可配多个目录实现冗余",
    "dfs.datanode.data.dir": "DataNode数据块在本地文件系统的存储目录，可指定多个磁盘路径分散IO",
    "dfs.blocksize": "HDFS数据块大小(字节)，默认134217728(128MB)。大文件适合大块，小文件适合小块",
    "dfs.namenode.http-address": "NameNode Web管理界面的HTTP服务地址和端口",
    "dfs.namenode.https-address": "NameNode HTTPS安全服务地址和端口",
    "dfs.namenode.secondary.http-address": "Secondary NameNode HTTP服务地址(非HA模式)",
    "dfs.permissions.enabled": "是否启用HDFS文件权限检查。实验环境关闭方便测试，生产环境必须启用",
    "dfs.permissions.superusergroup": "HDFS超级用户组，组成员拥有所有文件的操作权限。默认supergroup",
    "dfs.namenode.heartbeat.recheck-interval": "NameNode检查DataNode心跳的间隔(毫秒)",
    "dfs.heartbeat.interval": "DataNode向NameNode发送心跳的间隔(秒)",
    "dfs.replication.max": "HDFS最大副本数量上限",
    "dfs.hosts": "允许连接NameNode的DataNode主机列表文件路径(白名单)",
    "dfs.hosts.exclude": "不允许连接NameNode的DataNode主机列表文件路径(黑名单/退役节点)",
    "dfs.client-use.datanode.hostname": "客户端连接DataNode时是否使用主机名而非IP地址。Docker环境建议true",
    "dfs.datanode.du.reserved": "DataNode保留的磁盘空间(字节)，防止磁盘写满导致系统异常",
    "dfs.datanode.max.transfer.threads": "DataNode最大数据传输线程数，即同时处理的IO请求数。默认4096",
    "dfs.namenode.safemode.threshold-pct": "安全模式退出阈值，已注册DataNode块数占总块数的百分比。默认0.999",
    "dfs.image.transfer.bandwidthPerSec": "fsimage传输带宽限制(字节/秒)，0表示无限制",
    "dfs.nameservices": "HDFS命名服务逻辑名称，HA模式下客户端使用此名称访问集群。如mycluster",
    "dfs.ha.namenodes.mycluster": "HA模式下NameNode的服务ID列表，逗号分隔。如nn1,nn2",
    "dfs.namenode.rpc-address.mycluster.nn1": "HA模式下nn1的RPC服务地址",
    "dfs.namenode.rpc-address.mycluster.nn2": "HA模式下nn2的RPC服务地址",
    "dfs.namenode.http-address.mycluster.nn1": "HA模式下nn1的HTTP服务地址",
    "dfs.namenode.http-address.mycluster.nn2": "HA模式下nn2的HTTP服务地址",
    "dfs.namenode.shared.edits.dir": "HA模式下NameNode共享编辑日志的JournalNode地址",
    "dfs.journalnode.edits.dir": "JournalNode存储编辑日志的本地目录(HA模式)",
    "dfs.client.failover.proxy.provider.mycluster": "HA模式下客户端故障转移代理提供者类",
    "dfs.ha.fencing.methods": "HA模式下NameNode隔离方法，防止脑裂。常用: sshfence, shell(/bin/true)",
    "dfs.ha.fencing.ssh.private-key-files": "HA隔离使用的SSH私钥文件路径",
    "dfs.ha.fencing.ssh.connect-timeout": "HA隔离SSH连接超时时间(毫秒)",
    "dfs.ha.automatic-failover.enabled": "是否启用HA自动故障转移，依赖ZooKeeper实现",
    "ha.zookeeper.quorum": "HA模式下ZooKeeper集群地址，用于自动故障转移",
    "ha.zookeeper.session-timeout.ms": "ZooKeeper会话超时时间(毫秒)，影响故障检测速度",
    "mapreduce.framework.name": "MapReduce运行框架，yarn表示在YARN上运行。local为本地模式",
    "mapreduce.map.memory.mb": "Map任务可使用的内存大小(MB)，YARN据此分配容器资源",
    "mapreduce.reduce.memory.mb": "Reduce任务可使用的内存大小(MB)，通常为Map的2倍",
    "mapreduce.map.java.opts": "Map任务JVM堆内存参数，应小于mapreduce.map.memory.mb",
    "mapreduce.reduce.java.opts": "Reduce任务JVM堆内存参数，应小于mapreduce.reduce.memory.mb",
    "mapreduce.application.classpath": "MapReduce应用程序的类路径，包含Hadoop依赖JAR包",
    "mapreduce.jobhistory.address": "MapReduce作业历史服务器RPC地址",
    "mapreduce.jobhistory.webapp.address": "MapReduce作业历史Web UI地址",
    "mapreduce.map.env": "Map任务的环境变量设置，如HADOOP_MAPRED_HOME=/opt/hadoop",
    "mapreduce.reduce.env": "Reduce任务的环境变量设置，如HADOOP_MAPRED_HOME=/opt/hadoop",
    "mapreduce.map.output.compress": "Map任务输出是否启用压缩，可减少Shuffle数据传输量",
    "mapreduce.map.output.compress.codec": "Map输出压缩编解码器，如org.apache.hadoop.io.compress.SnappyCodec",
    "yarn.app.mapreduce.am.env": "MapReduce ApplicationMaster环境变量，如HADOOP_MAPRED_HOME=/opt/hadoop",
    "yarn.resourcemanager.hostname": "YARN ResourceManager主机名",
    "yarn.nodemanager.aux-services": "NodeManager辅助服务，mapreduce_shuffle是运行MR作业必须的",
    "yarn.nodemanager.resource.memory-mb": "NodeManager可分配给容器的总物理内存(MB)",
    "yarn.nodemanager.resource.cpu-vcores": "NodeManager可分配给容器的虚拟CPU核心数",
    "yarn.scheduler.minimum-allocation-mb": "YARN调度器单个容器最小可分配内存(MB)",
    "yarn.scheduler.maximum-allocation-mb": "YARN调度器单个容器最大可分配内存(MB)",
    "yarn.resourcemanager.address": "ResourceManager服务地址，客户端通过此地址提交应用",
    "yarn.resourcemanager.scheduler.address": "ResourceManager调度器服务地址",
    "yarn.resourcemanager.scheduler.class": "YARN调度器实现类: CapacityScheduler, FairScheduler, FIFO",
    "yarn.log-aggregation-enable": "是否启用日志聚合，将容器日志集中存储到HDFS",
    "yarn.nodemanager.vmem-check-enabled": "是否启用虚拟内存检查，关闭可避免容器因虚拟内存超限被杀",
    "yarn.nodemanager.pmem-check-enabled": "是否启用物理内存检查，关闭可避免容器因内存超限被杀",
    "yarn.nodemanager.log-dirs": "NodeManager容器日志的本地存储目录，可指定多个路径分散IO",
    "yarn.nodemanager.env-whitelist": "NodeManager传递给容器的环境变量白名单，逗号分隔",
    "yarn.application.classpath": "YARN应用程序的类路径，包含Hadoop相关JAR包",
    "yarn.resourcemanager.ha.enabled": "是否启用ResourceManager高可用",
    "yarn.resourcemanager.cluster-id": "ResourceManager HA集群ID，用于ZooKeeper区分不同集群",
    "yarn.resourcemanager.ha.rm-ids": "ResourceManager HA模式下的RM ID列表，如rm1,rm2",
    "yarn.resourcemanager.hostname.rm1": "HA模式下rm1的主机名",
    "yarn.resourcemanager.hostname.rm2": "HA模式下rm2的主机名",
    "yarn.resourcemanager.webapp.address.rm1": "HA模式下rm1的Web UI地址",
    "yarn.resourcemanager.webapp.address.rm2": "HA模式下rm2的Web UI地址",
    "yarn.resourcemanager.zk-address": "HA模式下ResourceManager使用的ZooKeeper地址",
    "yarn.resourcemanager.recovery.enabled": "是否启用ResourceManager状态恢复，重启后可恢复任务",
    "yarn.resourcemanager.store.class": "ResourceManager状态存储实现类，ZKRMStateStore使用ZooKeeper存储",
    "broker.id": "Kafka Broker在集群中的唯一标识符，正整数，每个Broker必须不同",
    "zookeeper.connect": "Kafka使用的ZooKeeper集群地址，逗号分隔。用于集群协调和元数据管理",
    "listeners": "Kafka Broker监听的网络地址和协议。PLAINTEXT为明文通信，生产环境应使用SSL",
    "advertised.listeners": "客户端实际连接Broker时使用的地址，容器环境中需使用容器名",
    "log.dirs": "Kafka消息日志的存储目录，Kafka将消息以日志文件形式存储在磁盘上",
    "num.partitions": "新创建主题的默认分区数量，分区是Kafka并行处理的基本单位",
    "default.replication.factor": "新创建主题的默认副本数量，提供数据冗余确保高可用。推荐3",
    "min.insync.replicas": "生产者确认消息写入所需的最小同步副本数，控制持久化可靠性级别",
    "delete.topic.enable": "是否允许通过管理工具删除主题，生产环境应谨慎启用",
    "num.io.threads": "Kafka处理网络请求的IO线程数量，应不少于磁盘数量",
    "num.network.threads": "Kafka处理网络请求的网络线程数量",
    "num.recovery.threads.per.data.dir": "每个数据目录用于日志恢复的线程数量",
    "offsets.topic.replication.factor": "内部offsets主题的副本数量，必须大于1确保可靠性",
    "transaction.state.log.replication.factor": "内部事务状态主题的副本数量",
    "transaction.state.log.min.isr": "事务状态主题的最小同步副本数",
    "log.retention.hours": "Kafka消息日志保留时间(小时)，超时后自动删除",
    "log.retention.bytes": "每个分区日志文件的最大字节数，-1表示无限制",
    "log.segment.bytes": "单个日志段文件的最大字节数",
    "zookeeper.connection.timeout.ms": "Kafka连接ZooKeeper的超时时间(毫秒)",
    "group.initial.rebalance.delay.ms": "消费者组首次再平衡的延迟时间(毫秒)",
    "log.cleanup.policy": "日志清理策略: delete(删除)或compact(压缩保留最新值)",
    "log.retention.check.interval.ms": "日志保留检查间隔(毫秒)",
    "log.segment.delete.delay.ms": "日志段删除延迟(毫秒)",
    "message.max.bytes": "单条消息最大字节数，默认1000012(约1MB)",
    "replica.fetch.max.bytes": "副本拉取消息的最大字节数",
    "socket.send.buffer.bytes": "Socket发送缓冲区大小(字节)",
    "socket.receive.buffer.bytes": "Socket接收缓冲区大小(字节)",
    "socket.request.max.bytes": "Socket请求最大字节数",
    "auto.create.topics.enable": "是否允许自动创建主题，生产环境建议关闭",
    "tickTime": "ZooKeeper基本时间单位(毫秒)，用于计算会话超时、心跳间隔等",
    "initLimit": "Followers与Leader建立连接的初始化超时时间(×tickTime)",
    "syncLimit": "Followers与Leader同步数据的超时时间(×tickTime)",
    "dataDir": "ZooKeeper数据快照的存储目录，包含集群状态信息和事务日志",
    "dataLogDir": "ZooKeeper事务日志的存储目录，所有写操作先记录到此确保持久化",
    "clientPort": "ZooKeeper服务监听客户端连接的端口，2181为标准端口",
    "4lw.commands.whitelist": "ZooKeeper四字命令白名单，*表示全部启用。生产环境应限制",
    "server.1": "ZooKeeper节点1的配置，格式: hostname:peerPort:leaderPort",
    "server.2": "ZooKeeper节点2的配置，格式: hostname:peerPort:leaderPort",
    "server.3": "ZooKeeper节点3的配置，格式: hostname:peerPort:leaderPort",
    "autopurge.snapRetainCount": "ZooKeeper自动清理时保留的快照数量",
    "autopurge.purgeInterval": "ZooKeeper自动清理间隔(小时)，0表示禁用",
    "maxClientCnxns": "ZooKeeper允许单个客户端的最大并发连接数",
    "globalOutstandingLimit": "ZooKeeper最大排队请求数，防止请求堆积导致OOM",
    "preAllocSize": "ZooKeeper事务日志预分配空间大小(KB)，减少磁盘寻道",
    "snapCount": "ZooKeeper每多少次事务生成一次快照",
    "hbase.rootdir": "HBase在HDFS中的存储根目录，所有表数据和元数据存储在此路径下",
    "hbase.cluster.distributed": "HBase集群模式。true=分布式(多节点), false=单机(开发测试)",
    "hbase.zookeeper.quorum": "HBase使用的ZooKeeper集群节点地址，逗号分隔",
    "hbase.zookeeper.property.clientPort": "ZooKeeper客户端连接端口",
    "hbase.zookeeper.property.dataDir": "ZooKeeper在容器内的数据存储目录",
    "hbase.master": "HBase Master服务绑定地址，如0.0.0.0表示监听所有接口",
    "hbase.master.info.port": "HBase Master Web管理界面的服务端口，默认16010",
    "hbase.master.port": "HBase Master RPC服务端口，默认16000",
    "hbase.regionserver.port": "HBase RegionServer RPC服务端口，默认16020",
    "hbase.regionserver.info.port": "HBase RegionServer Web UI端口，默认16030",
    "hbase.unsafe.stream.capability.enforce": "强制关闭流能力检查，允许在不支持hflush的HDFS上运行HBase",
    "hbase.client.scanner.timeout.period": "客户端扫描操作超时时间(毫秒)，默认60000",
    "hbase.rpc.timeout": "HBase RPC调用超时时间(毫秒)，默认60000",
    "hbase.master.maxclockskew": "Master与RegionServer之间允许的最大时钟偏差(毫秒)",
    "hbase.rest.port": "HBase REST服务端口，默认8080",
    "hbase.thrift.port": "HBase Thrift服务端口，默认9090",
    "hbase.hregion.maxfilesize": "HBase Region最大文件大小(字节)，超过自动分裂。默认10737418240(10GB)",
    "hbase.hregion.memstoreflush.size": "MemStore刷新到HDFS的大小阈值(字节)，默认134217728(128MB)",
    "hbase.regionserver.handler.count": "RegionServer RPC处理线程数，默认30。高并发可增大",
    "hbase.client.retries.number": "客户端重试次数，默认31",
    "hbase.ipc.client.tcpnodelay": "是否禁用Nagle算法，true可降低RPC延迟",
    "hbase.server.keyvalue.maxsize": "单个KeyValue最大字节数，防止过大数据导致OOM",
    "query.server.port": "HBase查询服务器端口",
    "javax.jdo.option.ConnectionURL": "Hive元数据存储的MySQL数据库JDBC连接URL",
    "javax.jdo.option.ConnectionDriverName": "MySQL JDBC驱动类名，如com.mysql.jdbc.Driver或com.mysql.cj.jdbc.Driver",
    "javax.jdo.option.ConnectionUserName": "连接MySQL数据库的用户名",
    "javax.jdo.option.ConnectionPassword": "连接MySQL数据库的密码",
    "hive.metastore.warehouse.dir": "Hive表数据在HDFS中的存储位置，默认/user/hive/warehouse",
    "hive.exec.scratchdir": "Hive查询执行过程中临时文件的存储位置",
    "hive.server2.thrift.port": "HiveServer2 Thrift服务端口，默认10000",
    "hive.server2.thrift.bind.host": "HiveServer2 Thrift服务绑定地址",
    "hive.metastore.uris": "Hive Metastore服务的Thrift URI地址",
    "hive.execution.engine": "Hive执行引擎。mr=MapReduce, tez=Tez, spark=Spark",
    "hive.support.concurrency": "是否启用Hive并发支持，启用后支持事务和并发写入",
    "hive.txn.manager": "Hive事务管理器类，DbTxnManager支持ACID事务",
    "hive.server2.enable.doAs": "HiveServer2是否以提交用户身份执行操作",
    "hive.exec.dynamic.partition": "是否启用动态分区",
    "hive.exec.dynamic.partition.mode": "动态分区模式。strict需指定至少一个静态分区，nonstrict无限制",
    "hive.exec.max.dynamic.partitions": "单个查询允许创建的最大动态分区总数，默认100",
    "hive.exec.max.dynamic.partitions.pernode": "每个Mapper/Reducer允许创建的最大动态分区数，默认100",
    "hive.optimize.sort.dynamic.partition": "是否优化动态分区排序，减少Reducer数量",
    "hive.stats.autogather": "是否自动收集表统计信息。关闭可避免StatsTask错误",
    "hive.stats.column.autogather": "是否自动收集列级统计信息",
    "hive.compute.query.using.stats": "是否使用统计信息优化查询计划",
    "hive.cli.print.header": "Hive CLI查询结果是否显示列名",
    "hive.cli.print.current.db": "Hive CLI提示符是否显示当前数据库名",
    "hive.metastore.schema.verification": "是否验证Metastore数据库Schema版本一致性",
    "hive.metastore.event.db.notification.api.auth": "Metastore事件通知是否需要认证",
    "hive.metastore.transactional.event.listeners": "Metastore事务性事件监听器类列表",
    "hive.server2.tez.initialize.default.sessions": "是否在HiveServer2启动时初始化Tez会话",
    "hive.server2.tez.default.sessions": "HiveServer2 Tez会话的默认配置",
    "hive.server2.authentication": "HiveServer2认证方式: NONE, KERBEROS, LDAP, CUSTOM等",
    "hive.server2.transport.mode": "HiveServer2传输模式: binary(Thrift)或http",
    "hive.metastore.db.type": "元数据数据库类型，如mysql, postgres, derby",
    "hive.optimize.mapjoin.mapreduce": "是否将MapJoin转换为MapReduce任务",
    "hive.auto.convert.join": "是否自动将Join转换为MapJoin(小表Join大表优化)",
    "hive.auto.convert.join.noconditionaltask.size": "自动MapJoin的小表大小阈值(字节)",
    "hive.exec.parallel": "是否启用并行执行多个Stage",
    "hive.exec.parallel.thread.number": "并行执行的线程数",
    "hive.map.aggr": "是否启用Map端聚合，减少Shuffle数据量",
    "hive.groupby.skewindata": "是否启用GroupBy数据倾斜优化，将一个MR拆为两个",
    "hive.optimize.reducededuplication": "是否启用Reduce去重优化",
    "hive.exec.reducers.bytes.per.reducer": "每个Reducer处理的数据量(字节)，默认256MB",
    "hive.exec.reducers.max": "最大Reducer数量，默认1009",
    "hive.input.format": "Hive输入格式，默认CombineHiveInputFormat合并小文件",
    "hive.merge.mapfiles": "MapOnly作业结束后是否合并小文件",
    "hive.merge.mapredfiles": "MapReduce作业结束后是否合并小文件",
    "hive.merge.size.per.task": "合并后每个文件的大小(字节)",
    "hive.merge.smallfiles.avgsize": "触发合并的平均文件大小阈值(字节)",
    "spark.master": "Spark集群Master服务地址，如 spark://spark-master:7077 或 yarn",
    "spark.app.name": "Spark应用程序的默认名称，在Web UI和日志中标识应用",
    "spark.driver.memory": "Spark Driver进程的堆内存大小，负责任务调度和结果收集",
    "spark.executor.memory": "每个Executor进程的堆内存大小，影响任务执行性能",
    "spark.executor.cores": "每个Executor可使用的CPU核心数量",
    "spark.executor.instances": "应用程序启动的Executor实例数量",
    "spark.eventLog.enabled": "是否启用Spark事件日志记录功能",
    "spark.eventLog.dir": "Spark事件日志在HDFS中的存储位置",
    "spark.history.fs.logDirectory": "Spark历史服务器读取事件日志的目录",
    "spark.yarn.historyServer.address": "YARN模式下历史服务器的服务地址",
    "spark.serializer": "Spark数据序列化器。Kryo比Java更高效，减少序列化开销",
    "spark.dynamicAllocation.enabled": "是否启用Spark动态资源分配，根据负载自动调整Executor数量",
    "spark.shuffle.service.enabled": "是否启用外部Shuffle服务，提高Shuffle操作稳定性和性能",
    "spark.sql.warehouse.dir": "Spark SQL数据仓库的存储目录",
    "spark.sql.shuffle.partitions": "Spark SQL Join和聚合操作的默认分区数，默认200",
    "spark.default.parallelism": "Spark RDD默认并行度，影响未指定分区数的操作",
    "spark.local.dir": "Spark本地临时文件存储目录，用于Shuffle和排序溢写",
    "spark.driver.extraJavaOptions": "Driver JVM额外选项，如GC参数 -XX:+UseG1GC",
    "spark.executor.extraJavaOptions": "Executor JVM额外选项，如GC参数 -XX:+UseG1GC",
    "spark.memory.fraction": "Spark执行和存储内存占堆内存的比例(0-1)，默认0.6",
    "spark.memory.storageFraction": "Spark存储内存占执行+存储总内存的比例(0-1)，默认0.5",
    "spark.scheduler.mode": "Spark调度模式: FIFO, FAIR",
    "spark.task.maxFailures": "任务最大失败次数，超过则整个作业失败。默认4",
    "spark.speculation": "是否启用推测执行，对慢任务启动备份任务",
    "spark.network.timeout": "Spark网络超时时间(秒)，默认120",
    "spark.executor.heartbeatInterval": "Executor心跳间隔(秒)，默认10",
    "spark.rpc.message.maxSize": "RPC消息最大大小(MB)，默认128",
    "spark.kryoserializer.buffer.max": "Kryo序列化最大缓冲区大小(MB)，默认64",
    "spark.streaming.backpressure.enabled": "是否启用Spark Streaming背压机制",
    "spark.streaming.kafka.maxRatePerPartition": "Kafka Direct Stream每分区每秒最大读取记录数",
    "JAVA_HOME": "Java运行环境安装路径",
    "HADOOP_CONF_DIR": "Hadoop配置文件目录路径，Spark需要读取Hadoop配置",
    "YARN_CONF_DIR": "YARN配置文件目录路径",
    "HADOOP_HOME": "Hadoop安装根目录",
    "SPARK_MASTER_HOST": "Spark Master服务绑定的主机名",
    "SPARK_MASTER_PORT": "Spark Master服务监听端口，默认7077",
    "SPARK_MASTER_WEBUI_PORT": "Spark Master Web UI端口，默认8080",
    "SPARK_WORKER_CORES": "每个Worker可使用的CPU核心数",
    "SPARK_WORKER_MEMORY": "每个Worker可使用的内存大小",
    "SPARK_WORKER_WEBUI_PORT": "Worker Web UI端口，默认8081",
    "SPARK_WORKER_DIR": "Spark Worker工作目录，存储应用运行时的临时文件",
    "SPARK_DAEMON_MEMORY": "Spark守护进程的内存大小",
    "SPARK_DAEMON_JAVA_OPTS": "Spark守护进程的JVM选项",
    "SPARK_HISTORY_OPTS": "Spark历史服务器的JVM选项",
    "SPARK_DIST_CLASSPATH": "Spark分布式类路径，包含Hadoop等依赖",
    "SPARK_LOCAL_IP": "Spark本机IP地址，多网卡环境需指定",
    "SPARK_PUBLIC_DNS": "Spark对外DNS名称，影响Web UI显示",
    "jobmanager.rpc.address": "Flink JobManager服务的网络地址，TaskManager通过此地址连接",
    "jobmanager.rpc.port": "JobManager RPC服务端口，6123为标准端口",
    "jobmanager.memory.process.size": "JobManager进程的总内存大小",
    "jobmanager.memory.heap.size": "JobManager JVM堆内存大小",
    "jobmanager.memory.off-heap.size": "JobManager堆外内存大小",
    "taskmanager.memory.process.size": "TaskManager进程的总内存大小",
    "taskmanager.memory.flink.size": "Flink TaskManager Flink框架使用的内存大小",
    "taskmanager.memory.task.heap.size": "Flink TaskManager任务堆内存大小",
    "taskmanager.memory.managed.size": "Flink TaskManager托管内存大小(排序、缓存等)",
    "taskmanager.memory.network.min": "Flink TaskManager网络缓冲区最小内存",
    "taskmanager.memory.network.max": "Flink TaskManager网络缓冲区最大内存",
    "taskmanager.numberOfTaskSlots": "每个TaskManager可并行执行的任务槽数量",
    "parallelism.default": "流处理任务的默认并行度",
    "state.backend": "Flink状态数据的存储后端。hashmap=内存, rocksdb=磁盘",
    "state.checkpoints.dir": "检查点数据的存储位置，用于故障恢复",
    "state.savepoints.dir": "保存点数据的存储位置，用于手动备份和版本升级",
    "high-availability": "Flink集群高可用性模式。none=禁用, zookeeper=启用",
    "high-availability.zookeeper.quorum": "HA模式下ZooKeeper集群地址",
    "high-availability.zookeeper.path.root": "HA模式下Flink在ZooKeeper中的根路径",
    "high-availability.storageDir": "HA模式下JobManager元数据持久化存储目录",
    "blob.server.port": "Flink Blob服务器端口，用于分发JAR包和用户代码",
    "query.server.port": "Flink查询服务器端口",
    "rest.port": "Flink REST API服务端口，默认8081",
    "rest.address": "Flink REST API服务监听地址",
    "classloader.resolve-order": "类加载器解析顺序。parent-first优先父类加载器",
    "web.submit.enable": "是否允许通过Web界面提交任务",
    "execution.checkpointing.interval": "Flink检查点触发间隔(毫秒)，影响故障恢复粒度",
    "execution.checkpointing.mode": "Flink检查点模式: EXACTLY_ONCE(精确一次)或AT_LEAST_ONCE(至少一次)",
    "execution.checkpointing.timeout": "检查点超时时间(毫秒)，默认600000(10分钟)",
    "execution.checkpointing.min-pause": "两次检查点之间的最小间隔(毫秒)",
    "execution.checkpointing.max-concurrent-checkpoints": "最大并发检查点数量，默认1",
    "restart-strategy": "Flink任务失败重启策略: fixed-delay, failure-rate, none",
    "restart-strategy.fixed-delay.attempts": "固定延迟重启策略的最大重启次数",
    "restart-strategy.fixed-delay.delay": "固定延迟重启策略的延迟时间",
    "restart-strategy.failure-rate.max-failures-per-interval": "失败率策略的间隔内最大失败次数",
    "restart-strategy.failure-rate.failure-rate-interval": "失败率策略的测量间隔",
    "restart-strategy.failure-rate.delay": "失败率策略的重启延迟",
    "taskmanager.memory.jvm-overhead.min": "JVM开销最小内存(本地内存、线程栈等)",
    "taskmanager.memory.jvm-overhead.max": "JVM开销最大内存",
    "taskmanager.memory.jvm-metaspace.size": "JVM Metaspace大小(类元数据)",
    "agent2.sources": "Flume Agent2的数据源组件列表，空格分隔",
    "agent2.sinks": "Flume Agent2的数据输出组件列表，空格分隔",
    "agent2.channels": "Flume Agent2的数据通道组件列表，空格分隔",
    "agent2.sources.log-source.type": "Flume数据源类型，exec表示执行命令获取数据",
    "agent2.sources.log-source.command": "exec数据源执行的命令，如tail -F持续读取日志",
    "agent2.sources.log-source.channels": "数据源连接的通道列表，空格分隔",
    "agent2.sources.log-source.batchSize": "数据源单次批量发送的事件数量",
    "agent2.sources.log-source.batchDurationMillis": "数据源批量发送的最大等待时间(毫秒)",
    "agent2.sources.log-source.restart": "exec Source执行命令失败后是否重启",
    "agent2.sources.log-source.logStdErr": "是否将命令的标准错误输出记录为事件",
    "agent2.sources.log-source.charset": "Source读取数据的字符编码，默认UTF-8",
    "agent2.sinks.kafka-sink.type": "Flume输出端类型，org.apache.flume.sink.KafkaSink发送到Kafka",
    "agent2.sinks.kafka-sink.topic": "Flume输出到Kafka的目标主题名称",
    "agent2.sinks.kafka-sink.brokerList": "Kafka Broker地址列表，逗号分隔",
    "agent2.sinks.kafka-sink.requiredAcks": "Kafka生产者确认模式: 0=不等确认, 1=Leader确认, -1=全部确认",
    "agent2.sinks.kafka-sink.batchSize": "Flume输出端单次批量发送的事件数量",
    "agent2.sinks.kafka-sink.channel": "输出端连接的通道名称",
    "agent2.sinks.kafka-sink.kafka.producer.sasl.mechanism": "Kafka SASL认证机制",
    "agent2.sinks.kafka-sink.kafka.security.protocol": "Kafka安全协议: PLAINTEXT, SSL, SASL_PLAINTEXT, SASL_SSL",
    "agent2.channels.memory-channel.type": "Flume通道类型，memory为内存通道(快但不持久)，file为文件通道",
    "agent2.channels.memory-channel.capacity": "内存通道中存储的最大事件数量",
    "agent2.channels.memory-channel.transactionCapacity": "单次事务中通道可处理的最大事件数量",
    "agent2.channels.memory-channel.keep-alive": "通道满时等待空间释放的超时时间(秒)",
    "agent2.channels.memory-channel.byteCapacityBufferPercentage": "字节容量缓冲百分比，默认20",
    "agent2.channels.memory-channel.byteCapacity": "通道最大字节容量，默认JVM堆内存的80%",
    "bind-address": "MySQL服务绑定的网络地址，0.0.0.0表示监听所有网络接口",
    "port": "MySQL服务监听端口，3306为标准端口",
    "character-set-server": "MySQL服务器默认字符集，utf8mb4支持完整Unicode包括emoji",
    "collation-server": "MySQL服务器默认排序规则，utf8mb4_unicode_ci支持多语言排序",
    "default-authentication-plugin": "MySQL默认认证插件，caching_sha2_password更安全，mysql_native_password兼容性好",
    "default-character-set": "MySQL客户端默认字符集",
    "max_connections": "MySQL允许的最大并发连接数",
    "innodb_buffer_pool_size": "InnoDB缓冲池大小，影响数据缓存和查询性能，建议设为物理内存60-80%",
    "innodb_log_file_size": "InnoDB重做日志文件大小，影响写入性能和恢复时间",
    "innodb_flush_log_at_trx_commit": "InnoDB日志刷盘策略: 0=每秒, 1=每次提交(最安全), 2=每秒+提交时OS缓存",
    "innodb_flush_method": "InnoDB数据刷新方法: O_DIRECT跳过OS缓存, fdatasync默认",
    "innodb_io_capacity": "InnoDB每秒IO操作数上限，SSD可设2000+，HDD建议200",
    "innodb_io_capacity_max": "InnoDB IO上限最大值，紧急情况下的IO上限",
    "innodb_lock_wait_timeout": "InnoDB锁等待超时时间(秒)，默认50",
    "innodb_file_per_table": "是否每个表使用独立表空间文件，便于回收磁盘空间",
    "sql_mode": "MySQL SQL模式，控制SQL语法验证严格程度。常用: STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION",
    "lower_case_table_names": "表名大小写敏感策略: 0=区分(默认Linux), 1=不区分(小写存储), 2=不区分(原样存储macOS)",
    "datadir": "MySQL数据文件存储目录",
    "socket": "MySQL Unix套接字文件路径",
    "pid-file": "MySQL进程PID文件路径",
    "skip-name-resolve": "MySQL是否跳过DNS反向解析，启用可加速连接建立",
    "user": "MySQL服务运行的用户名",
    "sync_binlog": "binlog同步频率: 0=OS控制, 1=每次提交同步(最安全), N=每N次提交同步",
    "binlog_format": "binlog格式: STATEMENT(语句), ROW(行), MIXED(混合)",
    "log_error": "MySQL错误日志文件路径",
    "slow_query_log": "是否启用慢查询日志",
    "long_query_time": "慢查询阈值(秒)，超过记录到慢查询日志",
    "tmp_table_size": "内存临时表最大大小",
    "max_heap_table_size": "MEMORY引擎表最大大小",
    "sort_buffer_size": "每个排序线程的缓冲区大小",
    "join_buffer_size": "每个Join操作的缓冲区大小",
    "read_buffer_size": "顺序读缓冲区大小",
    "read_rnd_buffer_size": "随机读缓冲区大小",
}

CORE_ITEMS = {
    "fs.defaultFS", "hadoop.tmp.dir",
    "dfs.replication",
    "dfs.namenode.name.dir", "dfs.datanode.data.dir",
    "dfs.nameservices", "dfs.ha.namenodes.mycluster",
    "dfs.namenode.rpc-address.mycluster.nn1",
    "dfs.namenode.rpc-address.mycluster.nn2",
    "dfs.namenode.shared.edits.dir",
    "dfs.ha.automatic-failover.enabled",
    "ha.zookeeper.quorum",
    "mapreduce.framework.name",
    "yarn.resourcemanager.hostname", "yarn.nodemanager.aux-services",
    "yarn.resourcemanager.ha.enabled",
    "yarn.resourcemanager.store.class",
    "broker.id", "zookeeper.connect", "listeners",
    "advertised.listeners", "log.dirs",
    "tickTime", "initLimit", "syncLimit",
    "dataDir", "clientPort",
    "hbase.rootdir", "hbase.cluster.distributed",
    "hbase.zookeeper.quorum",
    "hbase.unsafe.stream.capability.enforce",
    "javax.jdo.option.ConnectionURL",
    "javax.jdo.option.ConnectionDriverName",
    "javax.jdo.option.ConnectionUserName",
    "javax.jdo.option.ConnectionPassword",
    "hive.metastore.warehouse.dir",
    "hive.metastore.uris",
    "spark.master", "spark.driver.memory",
    "spark.executor.memory",
    "JAVA_HOME", "HADOOP_CONF_DIR",
    "SPARK_MASTER_HOST", "SPARK_MASTER_PORT",
    "SPARK_WORKER_MEMORY",
    "jobmanager.rpc.address", "jobmanager.rpc.port",
    "taskmanager.memory.process.size",
    "taskmanager.numberOfTaskSlots",
    "rest.port", "rest.address",
    "agent2.sources", "agent2.sinks", "agent2.channels",
    "agent2.sources.log-source.type",
    "agent2.sources.log-source.command",
    "agent2.sources.log-source.channels",
    "agent2.sinks.kafka-sink.type",
    "agent2.sinks.kafka-sink.topic",
    "agent2.sinks.kafka-sink.brokerList",
    "agent2.sinks.kafka-sink.channel",
    "agent2.channels.memory-channel.type",
    "agent2.channels.memory-channel.capacity",
    "agent2.channels.memory-channel.transactionCapacity",
    "bind-address", "port",
    "character-set-server",
}

PRESET_ITEMS = {
    "hadoop": {
        "core-site.xml": [
            "fs.defaultFS", "hadoop.tmp.dir", "hadoop.http.staticuser.user",
            "io.file.buffer.size", "io.compression.codecs",
            "io.serializations",
            "hadoop.security.authentication", "hadoop.security.authorization",
            "hadoop.proxyuser.root.hosts", "hadoop.proxyuser.root.groups",
            "hadoop.proxyuser.httpfs.hosts", "hadoop.proxyuser.httpfs.groups",
            "hadoop.proxyuser.hive.hosts", "hadoop.proxyuser.hive.groups",
        ],
        "hdfs-site.xml": [
            "dfs.replication", "dfs.namenode.name.dir", "dfs.datanode.data.dir",
            "dfs.blocksize", "dfs.permissions.enabled",
            "dfs.permissions.superusergroup",
            "dfs.namenode.http-address", "dfs.namenode.https-address",
            "dfs.namenode.secondary.http-address",
            "dfs.namenode.heartbeat.recheck-interval", "dfs.heartbeat.interval",
            "dfs.replication.max", "dfs.hosts", "dfs.hosts.exclude",
            "dfs.client-use.datanode.hostname",
            "dfs.datanode.du.reserved",
            "dfs.datanode.max.transfer.threads",
            "dfs.namenode.safemode.threshold-pct",
            "dfs.image.transfer.bandwidthPerSec",
        ],
        "mapred-site.xml": [
            "mapreduce.framework.name", "mapreduce.map.memory.mb",
            "mapreduce.reduce.memory.mb", "mapreduce.map.java.opts",
            "mapreduce.reduce.java.opts", "mapreduce.application.classpath",
            "mapreduce.jobhistory.address", "mapreduce.jobhistory.webapp.address",
            "mapreduce.map.env", "mapreduce.reduce.env",
            "yarn.app.mapreduce.am.env",
            "mapreduce.map.output.compress",
            "mapreduce.map.output.compress.codec",
        ],
        "yarn-site.xml": [
            "yarn.resourcemanager.hostname", "yarn.nodemanager.aux-services",
            "yarn.nodemanager.resource.memory-mb",
            "yarn.nodemanager.resource.cpu-vcores",
            "yarn.scheduler.minimum-allocation-mb",
            "yarn.scheduler.maximum-allocation-mb",
            "yarn.resourcemanager.address",
            "yarn.resourcemanager.scheduler.address",
            "yarn.resourcemanager.scheduler.class",
            "yarn.log-aggregation-enable",
            "yarn.nodemanager.vmem-check-enabled",
            "yarn.nodemanager.pmem-check-enabled",
            "yarn.nodemanager.log-dirs",
            "yarn.nodemanager.env-whitelist",
            "yarn.application.classpath",
        ],
        "workers": [],
    },
    "hadoop-ha": {
        "core-site.xml": [
            "fs.defaultFS", "hadoop.tmp.dir", "hadoop.http.staticuser.user",
            "ha.zookeeper.quorum", "ha.zookeeper.session-timeout.ms",
            "io.file.buffer.size",
        ],
        "hdfs-site.xml": [
            "dfs.nameservices", "dfs.ha.namenodes.mycluster",
            "dfs.namenode.rpc-address.mycluster.nn1",
            "dfs.namenode.rpc-address.mycluster.nn2",
            "dfs.namenode.http-address.mycluster.nn1",
            "dfs.namenode.http-address.mycluster.nn2",
            "dfs.namenode.shared.edits.dir",
            "dfs.journalnode.edits.dir",
            "dfs.client.failover.proxy.provider.mycluster",
            "dfs.ha.fencing.methods",
            "dfs.ha.fencing.ssh.private-key-files",
            "dfs.ha.fencing.ssh.connect-timeout",
            "dfs.ha.automatic-failover.enabled",
            "dfs.replication", "dfs.permissions.enabled",
            "dfs.blocksize", "dfs.namenode.name.dir",
            "dfs.datanode.data.dir",
        ],
        "mapred-site.xml": [
            "mapreduce.framework.name", "mapreduce.map.memory.mb",
            "mapreduce.reduce.memory.mb", "mapreduce.application.classpath",
            "mapreduce.jobhistory.address", "mapreduce.jobhistory.webapp.address",
            "mapreduce.map.env", "mapreduce.reduce.env",
            "yarn.app.mapreduce.am.env",
        ],
        "yarn-site.xml": [
            "yarn.resourcemanager.ha.enabled",
            "yarn.resourcemanager.cluster-id",
            "yarn.resourcemanager.ha.rm-ids",
            "yarn.resourcemanager.hostname.rm1",
            "yarn.resourcemanager.hostname.rm2",
            "yarn.resourcemanager.webapp.address.rm1",
            "yarn.resourcemanager.webapp.address.rm2",
            "yarn.resourcemanager.zk-address",
            "yarn.resourcemanager.recovery.enabled",
            "yarn.resourcemanager.store.class",
            "yarn.nodemanager.aux-services",
            "yarn.nodemanager.env-whitelist",
            "yarn.nodemanager.vmem-check-enabled",
            "yarn.nodemanager.resource.memory-mb",
            "yarn.log-aggregation-enable",
            "yarn.application.classpath",
        ],
        "workers": [],
    },
    "zookeeper": {
        "zoo.cfg": [
            "tickTime", "initLimit", "syncLimit", "dataDir", "dataLogDir",
            "clientPort", "4lw.commands.whitelist", "maxClientCnxns",
            "autopurge.snapRetainCount", "autopurge.purgeInterval",
            "globalOutstandingLimit", "preAllocSize", "snapCount",
            "server.1", "server.2", "server.3",
        ],
    },
    "hbase": {
        "hbase-site.xml": [
            "hbase.rootdir", "hbase.cluster.distributed",
            "hbase.zookeeper.quorum", "hbase.zookeeper.property.clientPort",
            "hbase.zookeeper.property.dataDir",
            "hbase.master", "hbase.master.info.port", "hbase.master.port",
            "hbase.regionserver.port", "hbase.regionserver.info.port",
            "hbase.unsafe.stream.capability.enforce",
            "hbase.client.scanner.timeout.period", "hbase.rpc.timeout",
            "hbase.master.maxclockskew",
            "hbase.rest.port", "hbase.thrift.port",
            "hbase.hregion.maxfilesize",
            "hbase.hregion.memstoreflush.size",
            "hbase.regionserver.handler.count",
            "hbase.client.retries.number",
            "hbase.ipc.client.tcpnodelay",
            "hbase.server.keyvalue.maxsize",
            "query.server.port",
        ],
        "regionservers": [],
    },
    "hive": {
        "hive-site.xml": [
            "javax.jdo.option.ConnectionURL",
            "javax.jdo.option.ConnectionDriverName",
            "javax.jdo.option.ConnectionUserName",
            "javax.jdo.option.ConnectionPassword",
            "hive.metastore.warehouse.dir", "hive.exec.scratchdir",
            "hive.server2.thrift.port", "hive.server2.thrift.bind.host",
            "hive.metastore.uris", "hive.execution.engine",
            "hive.support.concurrency", "hive.txn.manager",
            "hive.server2.enable.doAs",
            "hive.exec.dynamic.partition", "hive.exec.dynamic.partition.mode",
            "hive.exec.max.dynamic.partitions",
            "hive.exec.max.dynamic.partitions.pernode",
            "hive.optimize.sort.dynamic.partition",
            "hive.stats.autogather", "hive.stats.column.autogather",
            "hive.compute.query.using.stats",
            "hive.cli.print.header", "hive.cli.print.current.db",
            "hive.metastore.schema.verification",
            "hive.metastore.event.db.notification.api.auth",
            "hive.metastore.transactional.event.listeners",
            "hive.server2.tez.initialize.default.sessions",
            "hive.server2.tez.default.sessions",
            "hive.server2.authentication",
            "hive.server2.transport.mode",
            "hive.metastore.db.type",
            "hive.optimize.mapjoin.mapreduce",
            "hive.auto.convert.join",
            "hive.auto.convert.join.noconditionaltask.size",
            "hive.exec.parallel", "hive.exec.parallel.thread.number",
            "hive.map.aggr", "hive.groupby.skewindata",
            "hive.optimize.reducededuplication",
            "hive.exec.reducers.bytes.per.reducer",
            "hive.exec.reducers.max",
            "hive.input.format",
            "hive.merge.mapfiles", "hive.merge.mapredfiles",
            "hive.merge.size.per.task", "hive.merge.smallfiles.avgsize",
        ],
    },
    "kafka": {
        "server.properties": [
            "broker.id", "zookeeper.connect", "listeners",
            "advertised.listeners", "log.dirs",
            "num.partitions", "default.replication.factor",
            "min.insync.replicas", "delete.topic.enable",
            "num.io.threads", "num.network.threads",
            "num.recovery.threads.per.data.dir",
            "offsets.topic.replication.factor",
            "transaction.state.log.replication.factor",
            "transaction.state.log.min.isr",
            "log.retention.hours", "log.retention.bytes",
            "log.segment.bytes",
            "log.cleanup.policy",
            "log.retention.check.interval.ms",
            "log.segment.delete.delay.ms",
            "message.max.bytes",
            "replica.fetch.max.bytes",
            "socket.send.buffer.bytes", "socket.receive.buffer.bytes",
            "socket.request.max.bytes",
            "zookeeper.connection.timeout.ms",
            "group.initial.rebalance.delay.ms",
            "auto.create.topics.enable",
        ],
        "server2.properties": [
            "broker.id", "zookeeper.connect", "listeners",
            "advertised.listeners", "log.dirs",
            "num.partitions", "default.replication.factor",
            "min.insync.replicas", "delete.topic.enable",
        ],
        "server3.properties": [
            "broker.id", "zookeeper.connect", "listeners",
            "advertised.listeners", "log.dirs",
            "num.partitions", "default.replication.factor",
            "min.insync.replicas", "delete.topic.enable",
        ],
    },
    "spark": {
        "spark-defaults.conf": [
            "spark.master", "spark.app.name",
            "spark.driver.memory", "spark.executor.memory",
            "spark.executor.cores", "spark.executor.instances",
            "spark.eventLog.enabled", "spark.eventLog.dir",
            "spark.history.fs.logDirectory",
            "spark.yarn.historyServer.address",
            "spark.serializer",
            "spark.dynamicAllocation.enabled",
            "spark.shuffle.service.enabled",
            "spark.sql.warehouse.dir", "spark.sql.shuffle.partitions",
            "spark.default.parallelism", "spark.local.dir",
            "spark.driver.extraJavaOptions",
            "spark.executor.extraJavaOptions",
            "spark.memory.fraction", "spark.memory.storageFraction",
            "spark.scheduler.mode",
            "spark.task.maxFailures",
            "spark.speculation",
            "spark.network.timeout",
            "spark.executor.heartbeatInterval",
            "spark.rpc.message.maxSize",
            "spark.kryoserializer.buffer.max",
            "spark.streaming.backpressure.enabled",
            "spark.streaming.kafka.maxRatePerPartition",
        ],
        "spark-env.sh": [
            "JAVA_HOME", "HADOOP_CONF_DIR", "YARN_CONF_DIR",
            "HADOOP_HOME",
            "SPARK_MASTER_HOST", "SPARK_MASTER_PORT",
            "SPARK_MASTER_WEBUI_PORT",
            "SPARK_WORKER_CORES", "SPARK_WORKER_MEMORY",
            "SPARK_WORKER_WEBUI_PORT", "SPARK_WORKER_DIR",
            "SPARK_DAEMON_MEMORY", "SPARK_DAEMON_JAVA_OPTS",
            "SPARK_HISTORY_OPTS",
            "SPARK_DIST_CLASSPATH",
            "SPARK_LOCAL_IP", "SPARK_PUBLIC_DNS",
        ],
        "slaves": [],
    },
    "flink": {
        "flink-conf.yaml": [
            "jobmanager.rpc.address", "jobmanager.rpc.port",
            "jobmanager.memory.process.size",
            "jobmanager.memory.heap.size",
            "jobmanager.memory.off-heap.size",
            "taskmanager.memory.process.size",
            "taskmanager.memory.flink.size",
            "taskmanager.memory.task.heap.size",
            "taskmanager.memory.managed.size",
            "taskmanager.memory.network.min",
            "taskmanager.memory.network.max",
            "taskmanager.numberOfTaskSlots",
            "parallelism.default",
            "state.backend", "state.checkpoints.dir", "state.savepoints.dir",
            "high-availability", "high-availability.zookeeper.quorum",
            "high-availability.zookeeper.path.root",
            "high-availability.storageDir",
            "blob.server.port", "query.server.port",
            "rest.port", "rest.address",
            "classloader.resolve-order", "web.submit.enable",
            "execution.checkpointing.interval",
            "execution.checkpointing.mode",
            "execution.checkpointing.timeout",
            "execution.checkpointing.min-pause",
            "execution.checkpointing.max-concurrent-checkpoints",
            "restart-strategy",
            "restart-strategy.fixed-delay.attempts",
            "restart-strategy.fixed-delay.delay",
            "restart-strategy.failure-rate.max-failures-per-interval",
            "restart-strategy.failure-rate.failure-rate-interval",
            "restart-strategy.failure-rate.delay",
            "taskmanager.memory.jvm-overhead.min",
            "taskmanager.memory.jvm-overhead.max",
            "taskmanager.memory.jvm-metaspace.size",
        ],
        "workers": [],
    },
    "flume": {
        "flume-kafka.conf": [
            "agent2.sources", "agent2.sinks", "agent2.channels",
            "agent2.sources.log-source.type",
            "agent2.sources.log-source.command",
            "agent2.sources.log-source.channels",
            "agent2.sources.log-source.batchSize",
            "agent2.sources.log-source.batchDurationMillis",
            "agent2.sources.log-source.restart",
            "agent2.sources.log-source.logStdErr",
            "agent2.sources.log-source.charset",
            "agent2.sinks.kafka-sink.type",
            "agent2.sinks.kafka-sink.topic",
            "agent2.sinks.kafka-sink.brokerList",
            "agent2.sinks.kafka-sink.requiredAcks",
            "agent2.sinks.kafka-sink.batchSize",
            "agent2.sinks.kafka-sink.channel",
            "agent2.sinks.kafka-sink.kafka.producer.sasl.mechanism",
            "agent2.sinks.kafka-sink.kafka.security.protocol",
            "agent2.channels.memory-channel.type",
            "agent2.channels.memory-channel.capacity",
            "agent2.channels.memory-channel.transactionCapacity",
            "agent2.channels.memory-channel.keep-alive",
            "agent2.channels.memory-channel.byteCapacityBufferPercentage",
            "agent2.channels.memory-channel.byteCapacity",
        ],
    },
    "mysql": {
        "my.cnf": [
            "bind-address", "port",
            "character-set-server", "collation-server",
            "default-authentication-plugin",
            "default-character-set",
            "max_connections",
            "innodb_buffer_pool_size", "innodb_log_file_size",
            "innodb_flush_log_at_trx_commit",
            "innodb_flush_method",
            "innodb_io_capacity", "innodb_io_capacity_max",
            "innodb_lock_wait_timeout",
            "innodb_file_per_table",
            "sql_mode", "lower_case_table_names",
            "datadir", "socket", "pid-file",
            "skip-name-resolve", "user",
            "sync_binlog", "binlog_format",
            "log_error",
            "slow_query_log", "long_query_time",
            "tmp_table_size", "max_heap_table_size",
            "sort_buffer_size", "join_buffer_size",
            "read_buffer_size", "read_rnd_buffer_size",
        ],
    },
}
